version: '3.8'

services:
  url-shortener:
    image: url-shortener
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url
    ports:
      - '8080:8080'
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=urlPassword
      - POSTGRES_USER=urlUser
      - POSTGRES_DB=url