version: '3.8'

services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=urlPassword
      - POSTGRES_USER=urlUser
      - POSTGRES_DB=url