spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url
    username: urlUser
    password: urlPassword
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: true
      file: docker-compose-dependencies.yml